[market]
mcycle_price = "0.000000000007"
mcycle_price_stake_token = "0.0001"
peak_prove_khz = 2400
max_mcycle_limit = 84400
max_journal_bytes = 1000000
min_deadline = 900
lookback_blocks = 300
max_stake = "5"
max_file_size = 3_000_000_000
max_concurrent_proofs = 1
max_concurrent_preflights = 2  # Double the concurrency to handle more orders
max_critical_task_retries = 10
lockin_priority_gas = 50000000
balance_warn_threshold = "0.015"
balance_error_threshold = "0.01"
stake_balance_warn_threshold = "4"
stake_balance_error_threshold = "3"

# NIZAMLESS PARAMETRELERI
reaper_grace_period_secs = 432000
reaper_interval_secs = 300
min_lock_out_time = 23
lock_delay_ms = 0
prove_adress = "https://base-mainnet.g.alchemy.com/v2/6opiBZPWbB1vwpOSYONPP"
block_number = 0
my_rpc_url = "https://base-mainnet.g.alchemy.com/v2/6opiBZPWbB1vwpOSYONPP"
allow_requestor_addresses = [
    "0xc2db89b2bd434ceac6c74fbc0b2ad3a280e66db0",
    "0x734df7809c4ef94da037449c287166d114503198",
    "0x2f08f5d80dEB0CECCb0f4eF3BaB46451a6C47E16",
]
# NIZAMLESS PARAMETRELERI BITIS

# If enabled, the order will be preflighted without constraints.
priority_requestor_addresses = [
    "0xc2db89b2bd434ceac6c74fbc0b2ad3a280e66db0",
    "0x734df7809c4ef94da037449c287166d114503198",
    "0x2f08f5d80dEB0CECCb0f4eF3BaB46451a6C47E16",
]
deny_requestor_addresses = [
    "0xc559d9bef7df0076f71a42ea58723f429652b789",
    "0x2693946791da99da78ac441aba6d5ce2bccd96d3",
    "0xc73c222d7d39778bf9212f23a8f4356ff7c1e77f",
    "0x3ee7d9175ec8bb9e16e8fd3abdef5a354b247528",
]

[prover]
bonsai_r0_zkvm_ver = "2.1.0"
status_poll_retry_count = 3
status_poll_ms = 1000
req_retry_count = 3
req_retry_sleep_ms = 500
proof_retry_count = 8
proof_retry_sleep_ms = 5000

[batcher]
batch_max_time = 120
min_batch_size = 1
block_deadline_buffer_secs = 180
txn_timeout = 300
single_txn_fulfill = true
withdraw = false
#max_submission_attempts = 10